// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: T3C.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_T3C_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_T3C_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_T3C_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_T3C_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_T3C_2eproto;
namespace t3c {
namespace protobuf {
class Engine;
struct EngineDefaultTypeInternal;
extern EngineDefaultTypeInternal _Engine_default_instance_;
class Phys_state;
struct Phys_stateDefaultTypeInternal;
extern Phys_stateDefaultTypeInternal _Phys_state_default_instance_;
class RC;
struct RCDefaultTypeInternal;
extern RCDefaultTypeInternal _RC_default_instance_;
class t3c;
struct t3cDefaultTypeInternal;
extern t3cDefaultTypeInternal _t3c_default_instance_;
}  // namespace protobuf
}  // namespace t3c
PROTOBUF_NAMESPACE_OPEN
template<> ::t3c::protobuf::Engine* Arena::CreateMaybeMessage<::t3c::protobuf::Engine>(Arena*);
template<> ::t3c::protobuf::Phys_state* Arena::CreateMaybeMessage<::t3c::protobuf::Phys_state>(Arena*);
template<> ::t3c::protobuf::RC* Arena::CreateMaybeMessage<::t3c::protobuf::RC>(Arena*);
template<> ::t3c::protobuf::t3c* Arena::CreateMaybeMessage<::t3c::protobuf::t3c>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace t3c {
namespace protobuf {

enum Frame : int {
  na = 0,
  cc = 1,
  mk = 2,
  uv = 3,
  Frame_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Frame_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Frame_IsValid(int value);
constexpr Frame Frame_MIN = na;
constexpr Frame Frame_MAX = uv;
constexpr int Frame_ARRAYSIZE = Frame_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Frame_descriptor();
template<typename T>
inline const std::string& Frame_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Frame>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Frame_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Frame_descriptor(), enum_t_value);
}
inline bool Frame_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Frame* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Frame>(
    Frame_descriptor(), name, value);
}
enum Mot : int {
  null = 0,
  cold = 1,
  hot = 2,
  armed = 3,
  Mot_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Mot_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Mot_IsValid(int value);
constexpr Mot Mot_MIN = null;
constexpr Mot Mot_MAX = armed;
constexpr int Mot_ARRAYSIZE = Mot_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Mot_descriptor();
template<typename T>
inline const std::string& Mot_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Mot>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Mot_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Mot_descriptor(), enum_t_value);
}
inline bool Mot_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Mot* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Mot>(
    Mot_descriptor(), name, value);
}
enum Sys_mode : int {
  off = 0,
  idle = 1,
  manual = 2,
  mission = 3,
  takeoff = 4,
  land = 5,
  patrol = 6,
  acro = 7,
  strike = 8,
  anchor = 9,
  Sys_mode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Sys_mode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Sys_mode_IsValid(int value);
constexpr Sys_mode Sys_mode_MIN = off;
constexpr Sys_mode Sys_mode_MAX = anchor;
constexpr int Sys_mode_ARRAYSIZE = Sys_mode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Sys_mode_descriptor();
template<typename T>
inline const std::string& Sys_mode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Sys_mode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Sys_mode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Sys_mode_descriptor(), enum_t_value);
}
inline bool Sys_mode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Sys_mode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Sys_mode>(
    Sys_mode_descriptor(), name, value);
}
enum Effector : int {
  none = 0,
  anc_drop = 1,
  anc_cut = 2,
  horn = 3,
  release = 4,
  Effector_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Effector_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Effector_IsValid(int value);
constexpr Effector Effector_MIN = none;
constexpr Effector Effector_MAX = release;
constexpr int Effector_ARRAYSIZE = Effector_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Effector_descriptor();
template<typename T>
inline const std::string& Effector_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Effector>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Effector_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Effector_descriptor(), enum_t_value);
}
inline bool Effector_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Effector* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Effector>(
    Effector_descriptor(), name, value);
}
// ===================================================================

class t3c final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:t3c.protobuf.t3c) */ {
 public:
  inline t3c() : t3c(nullptr) {}
  ~t3c() override;
  explicit PROTOBUF_CONSTEXPR t3c(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  t3c(const t3c& from);
  t3c(t3c&& from) noexcept
    : t3c() {
    *this = ::std::move(from);
  }

  inline t3c& operator=(const t3c& from) {
    CopyFrom(from);
    return *this;
  }
  inline t3c& operator=(t3c&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const t3c& default_instance() {
    return *internal_default_instance();
  }
  static inline const t3c* internal_default_instance() {
    return reinterpret_cast<const t3c*>(
               &_t3c_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(t3c& a, t3c& b) {
    a.Swap(&b);
  }
  inline void Swap(t3c* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(t3c* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  t3c* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<t3c>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const t3c& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const t3c& from) {
    t3c::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(t3c* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "t3c.protobuf.t3c";
  }
  protected:
  explicit t3c(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPhysStateFieldNumber = 11,
    kRcMsgFieldNumber = 12,
    kEngFieldNumber = 13,
    kIdFieldNumber = 1,
    kFrameFieldNumber = 2,
    kVbatFieldNumber = 3,
    kUpTimeFieldNumber = 4,
    kRSSIFieldNumber = 5,
    kHbFieldNumber = 6,
    kSelectedFieldNumber = 7,
    kMotFieldNumber = 8,
    kSysFieldNumber = 9,
    kEffFieldNumber = 10,
  };
  // .t3c.protobuf.Phys_state phys_state = 11;
  bool has_phys_state() const;
  private:
  bool _internal_has_phys_state() const;
  public:
  void clear_phys_state();
  const ::t3c::protobuf::Phys_state& phys_state() const;
  PROTOBUF_NODISCARD ::t3c::protobuf::Phys_state* release_phys_state();
  ::t3c::protobuf::Phys_state* mutable_phys_state();
  void set_allocated_phys_state(::t3c::protobuf::Phys_state* phys_state);
  private:
  const ::t3c::protobuf::Phys_state& _internal_phys_state() const;
  ::t3c::protobuf::Phys_state* _internal_mutable_phys_state();
  public:
  void unsafe_arena_set_allocated_phys_state(
      ::t3c::protobuf::Phys_state* phys_state);
  ::t3c::protobuf::Phys_state* unsafe_arena_release_phys_state();

  // .t3c.protobuf.RC rc_msg = 12;
  bool has_rc_msg() const;
  private:
  bool _internal_has_rc_msg() const;
  public:
  void clear_rc_msg();
  const ::t3c::protobuf::RC& rc_msg() const;
  PROTOBUF_NODISCARD ::t3c::protobuf::RC* release_rc_msg();
  ::t3c::protobuf::RC* mutable_rc_msg();
  void set_allocated_rc_msg(::t3c::protobuf::RC* rc_msg);
  private:
  const ::t3c::protobuf::RC& _internal_rc_msg() const;
  ::t3c::protobuf::RC* _internal_mutable_rc_msg();
  public:
  void unsafe_arena_set_allocated_rc_msg(
      ::t3c::protobuf::RC* rc_msg);
  ::t3c::protobuf::RC* unsafe_arena_release_rc_msg();

  // .t3c.protobuf.Engine eng = 13;
  bool has_eng() const;
  private:
  bool _internal_has_eng() const;
  public:
  void clear_eng();
  const ::t3c::protobuf::Engine& eng() const;
  PROTOBUF_NODISCARD ::t3c::protobuf::Engine* release_eng();
  ::t3c::protobuf::Engine* mutable_eng();
  void set_allocated_eng(::t3c::protobuf::Engine* eng);
  private:
  const ::t3c::protobuf::Engine& _internal_eng() const;
  ::t3c::protobuf::Engine* _internal_mutable_eng();
  public:
  void unsafe_arena_set_allocated_eng(
      ::t3c::protobuf::Engine* eng);
  ::t3c::protobuf::Engine* unsafe_arena_release_eng();

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // .t3c.protobuf.Frame frame = 2;
  void clear_frame();
  ::t3c::protobuf::Frame frame() const;
  void set_frame(::t3c::protobuf::Frame value);
  private:
  ::t3c::protobuf::Frame _internal_frame() const;
  void _internal_set_frame(::t3c::protobuf::Frame value);
  public:

  // float vbat = 3;
  void clear_vbat();
  float vbat() const;
  void set_vbat(float value);
  private:
  float _internal_vbat() const;
  void _internal_set_vbat(float value);
  public:

  // int32 upTime = 4;
  void clear_uptime();
  int32_t uptime() const;
  void set_uptime(int32_t value);
  private:
  int32_t _internal_uptime() const;
  void _internal_set_uptime(int32_t value);
  public:

  // int32 RSSI = 5;
  void clear_rssi();
  int32_t rssi() const;
  void set_rssi(int32_t value);
  private:
  int32_t _internal_rssi() const;
  void _internal_set_rssi(int32_t value);
  public:

  // bool hb = 6;
  void clear_hb();
  bool hb() const;
  void set_hb(bool value);
  private:
  bool _internal_hb() const;
  void _internal_set_hb(bool value);
  public:

  // bool selected = 7;
  void clear_selected();
  bool selected() const;
  void set_selected(bool value);
  private:
  bool _internal_selected() const;
  void _internal_set_selected(bool value);
  public:

  // .t3c.protobuf.Mot mot = 8;
  void clear_mot();
  ::t3c::protobuf::Mot mot() const;
  void set_mot(::t3c::protobuf::Mot value);
  private:
  ::t3c::protobuf::Mot _internal_mot() const;
  void _internal_set_mot(::t3c::protobuf::Mot value);
  public:

  // .t3c.protobuf.Sys_mode sys = 9;
  void clear_sys();
  ::t3c::protobuf::Sys_mode sys() const;
  void set_sys(::t3c::protobuf::Sys_mode value);
  private:
  ::t3c::protobuf::Sys_mode _internal_sys() const;
  void _internal_set_sys(::t3c::protobuf::Sys_mode value);
  public:

  // .t3c.protobuf.Effector eff = 10;
  void clear_eff();
  ::t3c::protobuf::Effector eff() const;
  void set_eff(::t3c::protobuf::Effector value);
  private:
  ::t3c::protobuf::Effector _internal_eff() const;
  void _internal_set_eff(::t3c::protobuf::Effector value);
  public:

  // @@protoc_insertion_point(class_scope:t3c.protobuf.t3c)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::t3c::protobuf::Phys_state* phys_state_;
    ::t3c::protobuf::RC* rc_msg_;
    ::t3c::protobuf::Engine* eng_;
    int32_t id_;
    int frame_;
    float vbat_;
    int32_t uptime_;
    int32_t rssi_;
    bool hb_;
    bool selected_;
    int mot_;
    int sys_;
    int eff_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_T3C_2eproto;
};
// -------------------------------------------------------------------

class Phys_state final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:t3c.protobuf.Phys_state) */ {
 public:
  inline Phys_state() : Phys_state(nullptr) {}
  ~Phys_state() override;
  explicit PROTOBUF_CONSTEXPR Phys_state(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Phys_state(const Phys_state& from);
  Phys_state(Phys_state&& from) noexcept
    : Phys_state() {
    *this = ::std::move(from);
  }

  inline Phys_state& operator=(const Phys_state& from) {
    CopyFrom(from);
    return *this;
  }
  inline Phys_state& operator=(Phys_state&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Phys_state& default_instance() {
    return *internal_default_instance();
  }
  static inline const Phys_state* internal_default_instance() {
    return reinterpret_cast<const Phys_state*>(
               &_Phys_state_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Phys_state& a, Phys_state& b) {
    a.Swap(&b);
  }
  inline void Swap(Phys_state* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Phys_state* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Phys_state* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Phys_state>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Phys_state& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Phys_state& from) {
    Phys_state::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Phys_state* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "t3c.protobuf.Phys_state";
  }
  protected:
  explicit Phys_state(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kModeFieldNumber = 6,
    kLatFieldNumber = 1,
    kLonFieldNumber = 2,
    kHeadingFieldNumber = 3,
    kAltFieldNumber = 4,
    kSpeedFieldNumber = 5,
  };
  // string mode = 6;
  void clear_mode();
  const std::string& mode() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_mode(ArgT0&& arg0, ArgT... args);
  std::string* mutable_mode();
  PROTOBUF_NODISCARD std::string* release_mode();
  void set_allocated_mode(std::string* mode);
  private:
  const std::string& _internal_mode() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_mode(const std::string& value);
  std::string* _internal_mutable_mode();
  public:

  // float lat = 1;
  void clear_lat();
  float lat() const;
  void set_lat(float value);
  private:
  float _internal_lat() const;
  void _internal_set_lat(float value);
  public:

  // float lon = 2;
  void clear_lon();
  float lon() const;
  void set_lon(float value);
  private:
  float _internal_lon() const;
  void _internal_set_lon(float value);
  public:

  // float heading = 3;
  void clear_heading();
  float heading() const;
  void set_heading(float value);
  private:
  float _internal_heading() const;
  void _internal_set_heading(float value);
  public:

  // float alt = 4;
  void clear_alt();
  float alt() const;
  void set_alt(float value);
  private:
  float _internal_alt() const;
  void _internal_set_alt(float value);
  public:

  // float speed = 5;
  void clear_speed();
  float speed() const;
  void set_speed(float value);
  private:
  float _internal_speed() const;
  void _internal_set_speed(float value);
  public:

  // @@protoc_insertion_point(class_scope:t3c.protobuf.Phys_state)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mode_;
    float lat_;
    float lon_;
    float heading_;
    float alt_;
    float speed_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_T3C_2eproto;
};
// -------------------------------------------------------------------

class RC final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:t3c.protobuf.RC) */ {
 public:
  inline RC() : RC(nullptr) {}
  ~RC() override;
  explicit PROTOBUF_CONSTEXPR RC(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RC(const RC& from);
  RC(RC&& from) noexcept
    : RC() {
    *this = ::std::move(from);
  }

  inline RC& operator=(const RC& from) {
    CopyFrom(from);
    return *this;
  }
  inline RC& operator=(RC&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RC& default_instance() {
    return *internal_default_instance();
  }
  static inline const RC* internal_default_instance() {
    return reinterpret_cast<const RC*>(
               &_RC_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RC& a, RC& b) {
    a.Swap(&b);
  }
  inline void Swap(RC* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RC* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RC* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RC>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RC& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RC& from) {
    RC::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RC* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "t3c.protobuf.RC";
  }
  protected:
  explicit RC(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kThrottleFieldNumber = 1,
    kRudderFieldNumber = 2,
    kRollFieldNumber = 3,
    kPitchFieldNumber = 4,
  };
  // int32 throttle = 1;
  void clear_throttle();
  int32_t throttle() const;
  void set_throttle(int32_t value);
  private:
  int32_t _internal_throttle() const;
  void _internal_set_throttle(int32_t value);
  public:

  // int32 rudder = 2;
  void clear_rudder();
  int32_t rudder() const;
  void set_rudder(int32_t value);
  private:
  int32_t _internal_rudder() const;
  void _internal_set_rudder(int32_t value);
  public:

  // int32 roll = 3;
  void clear_roll();
  int32_t roll() const;
  void set_roll(int32_t value);
  private:
  int32_t _internal_roll() const;
  void _internal_set_roll(int32_t value);
  public:

  // int32 pitch = 4;
  void clear_pitch();
  int32_t pitch() const;
  void set_pitch(int32_t value);
  private:
  int32_t _internal_pitch() const;
  void _internal_set_pitch(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:t3c.protobuf.RC)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t throttle_;
    int32_t rudder_;
    int32_t roll_;
    int32_t pitch_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_T3C_2eproto;
};
// -------------------------------------------------------------------

class Engine final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:t3c.protobuf.Engine) */ {
 public:
  inline Engine() : Engine(nullptr) {}
  ~Engine() override;
  explicit PROTOBUF_CONSTEXPR Engine(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Engine(const Engine& from);
  Engine(Engine&& from) noexcept
    : Engine() {
    *this = ::std::move(from);
  }

  inline Engine& operator=(const Engine& from) {
    CopyFrom(from);
    return *this;
  }
  inline Engine& operator=(Engine&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Engine& default_instance() {
    return *internal_default_instance();
  }
  static inline const Engine* internal_default_instance() {
    return reinterpret_cast<const Engine*>(
               &_Engine_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Engine& a, Engine& b) {
    a.Swap(&b);
  }
  inline void Swap(Engine* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Engine* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Engine* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Engine>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Engine& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Engine& from) {
    Engine::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Engine* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "t3c.protobuf.Engine";
  }
  protected:
  explicit Engine(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRpmFieldNumber = 2,
    kKeyFieldNumber = 1,
    kEngStateFieldNumber = 3,
    kFuelFieldNumber = 4,
    kUptimeFieldNumber = 5,
    kMotStateFieldNumber = 6,
  };
  // int32 rpm = 2;
  void clear_rpm();
  int32_t rpm() const;
  void set_rpm(int32_t value);
  private:
  int32_t _internal_rpm() const;
  void _internal_set_rpm(int32_t value);
  public:

  // bool key = 1;
  void clear_key();
  bool key() const;
  void set_key(bool value);
  private:
  bool _internal_key() const;
  void _internal_set_key(bool value);
  public:

  // bool eng_state = 3;
  void clear_eng_state();
  bool eng_state() const;
  void set_eng_state(bool value);
  private:
  bool _internal_eng_state() const;
  void _internal_set_eng_state(bool value);
  public:

  // int32 fuel = 4;
  void clear_fuel();
  int32_t fuel() const;
  void set_fuel(int32_t value);
  private:
  int32_t _internal_fuel() const;
  void _internal_set_fuel(int32_t value);
  public:

  // int32 uptime = 5;
  void clear_uptime();
  int32_t uptime() const;
  void set_uptime(int32_t value);
  private:
  int32_t _internal_uptime() const;
  void _internal_set_uptime(int32_t value);
  public:

  // int32 mot_state = 6;
  void clear_mot_state();
  int32_t mot_state() const;
  void set_mot_state(int32_t value);
  private:
  int32_t _internal_mot_state() const;
  void _internal_set_mot_state(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:t3c.protobuf.Engine)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t rpm_;
    bool key_;
    bool eng_state_;
    int32_t fuel_;
    int32_t uptime_;
    int32_t mot_state_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_T3C_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// t3c

// int32 id = 1;
inline void t3c::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t t3c::_internal_id() const {
  return _impl_.id_;
}
inline int32_t t3c::id() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.t3c.id)
  return _internal_id();
}
inline void t3c::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void t3c::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.t3c.id)
}

// .t3c.protobuf.Frame frame = 2;
inline void t3c::clear_frame() {
  _impl_.frame_ = 0;
}
inline ::t3c::protobuf::Frame t3c::_internal_frame() const {
  return static_cast< ::t3c::protobuf::Frame >(_impl_.frame_);
}
inline ::t3c::protobuf::Frame t3c::frame() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.t3c.frame)
  return _internal_frame();
}
inline void t3c::_internal_set_frame(::t3c::protobuf::Frame value) {
  
  _impl_.frame_ = value;
}
inline void t3c::set_frame(::t3c::protobuf::Frame value) {
  _internal_set_frame(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.t3c.frame)
}

// float vbat = 3;
inline void t3c::clear_vbat() {
  _impl_.vbat_ = 0;
}
inline float t3c::_internal_vbat() const {
  return _impl_.vbat_;
}
inline float t3c::vbat() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.t3c.vbat)
  return _internal_vbat();
}
inline void t3c::_internal_set_vbat(float value) {
  
  _impl_.vbat_ = value;
}
inline void t3c::set_vbat(float value) {
  _internal_set_vbat(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.t3c.vbat)
}

// int32 upTime = 4;
inline void t3c::clear_uptime() {
  _impl_.uptime_ = 0;
}
inline int32_t t3c::_internal_uptime() const {
  return _impl_.uptime_;
}
inline int32_t t3c::uptime() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.t3c.upTime)
  return _internal_uptime();
}
inline void t3c::_internal_set_uptime(int32_t value) {
  
  _impl_.uptime_ = value;
}
inline void t3c::set_uptime(int32_t value) {
  _internal_set_uptime(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.t3c.upTime)
}

// int32 RSSI = 5;
inline void t3c::clear_rssi() {
  _impl_.rssi_ = 0;
}
inline int32_t t3c::_internal_rssi() const {
  return _impl_.rssi_;
}
inline int32_t t3c::rssi() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.t3c.RSSI)
  return _internal_rssi();
}
inline void t3c::_internal_set_rssi(int32_t value) {
  
  _impl_.rssi_ = value;
}
inline void t3c::set_rssi(int32_t value) {
  _internal_set_rssi(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.t3c.RSSI)
}

// bool hb = 6;
inline void t3c::clear_hb() {
  _impl_.hb_ = false;
}
inline bool t3c::_internal_hb() const {
  return _impl_.hb_;
}
inline bool t3c::hb() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.t3c.hb)
  return _internal_hb();
}
inline void t3c::_internal_set_hb(bool value) {
  
  _impl_.hb_ = value;
}
inline void t3c::set_hb(bool value) {
  _internal_set_hb(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.t3c.hb)
}

// bool selected = 7;
inline void t3c::clear_selected() {
  _impl_.selected_ = false;
}
inline bool t3c::_internal_selected() const {
  return _impl_.selected_;
}
inline bool t3c::selected() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.t3c.selected)
  return _internal_selected();
}
inline void t3c::_internal_set_selected(bool value) {
  
  _impl_.selected_ = value;
}
inline void t3c::set_selected(bool value) {
  _internal_set_selected(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.t3c.selected)
}

// .t3c.protobuf.Mot mot = 8;
inline void t3c::clear_mot() {
  _impl_.mot_ = 0;
}
inline ::t3c::protobuf::Mot t3c::_internal_mot() const {
  return static_cast< ::t3c::protobuf::Mot >(_impl_.mot_);
}
inline ::t3c::protobuf::Mot t3c::mot() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.t3c.mot)
  return _internal_mot();
}
inline void t3c::_internal_set_mot(::t3c::protobuf::Mot value) {
  
  _impl_.mot_ = value;
}
inline void t3c::set_mot(::t3c::protobuf::Mot value) {
  _internal_set_mot(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.t3c.mot)
}

// .t3c.protobuf.Sys_mode sys = 9;
inline void t3c::clear_sys() {
  _impl_.sys_ = 0;
}
inline ::t3c::protobuf::Sys_mode t3c::_internal_sys() const {
  return static_cast< ::t3c::protobuf::Sys_mode >(_impl_.sys_);
}
inline ::t3c::protobuf::Sys_mode t3c::sys() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.t3c.sys)
  return _internal_sys();
}
inline void t3c::_internal_set_sys(::t3c::protobuf::Sys_mode value) {
  
  _impl_.sys_ = value;
}
inline void t3c::set_sys(::t3c::protobuf::Sys_mode value) {
  _internal_set_sys(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.t3c.sys)
}

// .t3c.protobuf.Effector eff = 10;
inline void t3c::clear_eff() {
  _impl_.eff_ = 0;
}
inline ::t3c::protobuf::Effector t3c::_internal_eff() const {
  return static_cast< ::t3c::protobuf::Effector >(_impl_.eff_);
}
inline ::t3c::protobuf::Effector t3c::eff() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.t3c.eff)
  return _internal_eff();
}
inline void t3c::_internal_set_eff(::t3c::protobuf::Effector value) {
  
  _impl_.eff_ = value;
}
inline void t3c::set_eff(::t3c::protobuf::Effector value) {
  _internal_set_eff(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.t3c.eff)
}

// .t3c.protobuf.Phys_state phys_state = 11;
inline bool t3c::_internal_has_phys_state() const {
  return this != internal_default_instance() && _impl_.phys_state_ != nullptr;
}
inline bool t3c::has_phys_state() const {
  return _internal_has_phys_state();
}
inline void t3c::clear_phys_state() {
  if (GetArenaForAllocation() == nullptr && _impl_.phys_state_ != nullptr) {
    delete _impl_.phys_state_;
  }
  _impl_.phys_state_ = nullptr;
}
inline const ::t3c::protobuf::Phys_state& t3c::_internal_phys_state() const {
  const ::t3c::protobuf::Phys_state* p = _impl_.phys_state_;
  return p != nullptr ? *p : reinterpret_cast<const ::t3c::protobuf::Phys_state&>(
      ::t3c::protobuf::_Phys_state_default_instance_);
}
inline const ::t3c::protobuf::Phys_state& t3c::phys_state() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.t3c.phys_state)
  return _internal_phys_state();
}
inline void t3c::unsafe_arena_set_allocated_phys_state(
    ::t3c::protobuf::Phys_state* phys_state) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.phys_state_);
  }
  _impl_.phys_state_ = phys_state;
  if (phys_state) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:t3c.protobuf.t3c.phys_state)
}
inline ::t3c::protobuf::Phys_state* t3c::release_phys_state() {
  
  ::t3c::protobuf::Phys_state* temp = _impl_.phys_state_;
  _impl_.phys_state_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::t3c::protobuf::Phys_state* t3c::unsafe_arena_release_phys_state() {
  // @@protoc_insertion_point(field_release:t3c.protobuf.t3c.phys_state)
  
  ::t3c::protobuf::Phys_state* temp = _impl_.phys_state_;
  _impl_.phys_state_ = nullptr;
  return temp;
}
inline ::t3c::protobuf::Phys_state* t3c::_internal_mutable_phys_state() {
  
  if (_impl_.phys_state_ == nullptr) {
    auto* p = CreateMaybeMessage<::t3c::protobuf::Phys_state>(GetArenaForAllocation());
    _impl_.phys_state_ = p;
  }
  return _impl_.phys_state_;
}
inline ::t3c::protobuf::Phys_state* t3c::mutable_phys_state() {
  ::t3c::protobuf::Phys_state* _msg = _internal_mutable_phys_state();
  // @@protoc_insertion_point(field_mutable:t3c.protobuf.t3c.phys_state)
  return _msg;
}
inline void t3c::set_allocated_phys_state(::t3c::protobuf::Phys_state* phys_state) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.phys_state_;
  }
  if (phys_state) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(phys_state);
    if (message_arena != submessage_arena) {
      phys_state = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, phys_state, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.phys_state_ = phys_state;
  // @@protoc_insertion_point(field_set_allocated:t3c.protobuf.t3c.phys_state)
}

// .t3c.protobuf.RC rc_msg = 12;
inline bool t3c::_internal_has_rc_msg() const {
  return this != internal_default_instance() && _impl_.rc_msg_ != nullptr;
}
inline bool t3c::has_rc_msg() const {
  return _internal_has_rc_msg();
}
inline void t3c::clear_rc_msg() {
  if (GetArenaForAllocation() == nullptr && _impl_.rc_msg_ != nullptr) {
    delete _impl_.rc_msg_;
  }
  _impl_.rc_msg_ = nullptr;
}
inline const ::t3c::protobuf::RC& t3c::_internal_rc_msg() const {
  const ::t3c::protobuf::RC* p = _impl_.rc_msg_;
  return p != nullptr ? *p : reinterpret_cast<const ::t3c::protobuf::RC&>(
      ::t3c::protobuf::_RC_default_instance_);
}
inline const ::t3c::protobuf::RC& t3c::rc_msg() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.t3c.rc_msg)
  return _internal_rc_msg();
}
inline void t3c::unsafe_arena_set_allocated_rc_msg(
    ::t3c::protobuf::RC* rc_msg) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rc_msg_);
  }
  _impl_.rc_msg_ = rc_msg;
  if (rc_msg) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:t3c.protobuf.t3c.rc_msg)
}
inline ::t3c::protobuf::RC* t3c::release_rc_msg() {
  
  ::t3c::protobuf::RC* temp = _impl_.rc_msg_;
  _impl_.rc_msg_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::t3c::protobuf::RC* t3c::unsafe_arena_release_rc_msg() {
  // @@protoc_insertion_point(field_release:t3c.protobuf.t3c.rc_msg)
  
  ::t3c::protobuf::RC* temp = _impl_.rc_msg_;
  _impl_.rc_msg_ = nullptr;
  return temp;
}
inline ::t3c::protobuf::RC* t3c::_internal_mutable_rc_msg() {
  
  if (_impl_.rc_msg_ == nullptr) {
    auto* p = CreateMaybeMessage<::t3c::protobuf::RC>(GetArenaForAllocation());
    _impl_.rc_msg_ = p;
  }
  return _impl_.rc_msg_;
}
inline ::t3c::protobuf::RC* t3c::mutable_rc_msg() {
  ::t3c::protobuf::RC* _msg = _internal_mutable_rc_msg();
  // @@protoc_insertion_point(field_mutable:t3c.protobuf.t3c.rc_msg)
  return _msg;
}
inline void t3c::set_allocated_rc_msg(::t3c::protobuf::RC* rc_msg) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.rc_msg_;
  }
  if (rc_msg) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(rc_msg);
    if (message_arena != submessage_arena) {
      rc_msg = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rc_msg, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.rc_msg_ = rc_msg;
  // @@protoc_insertion_point(field_set_allocated:t3c.protobuf.t3c.rc_msg)
}

// .t3c.protobuf.Engine eng = 13;
inline bool t3c::_internal_has_eng() const {
  return this != internal_default_instance() && _impl_.eng_ != nullptr;
}
inline bool t3c::has_eng() const {
  return _internal_has_eng();
}
inline void t3c::clear_eng() {
  if (GetArenaForAllocation() == nullptr && _impl_.eng_ != nullptr) {
    delete _impl_.eng_;
  }
  _impl_.eng_ = nullptr;
}
inline const ::t3c::protobuf::Engine& t3c::_internal_eng() const {
  const ::t3c::protobuf::Engine* p = _impl_.eng_;
  return p != nullptr ? *p : reinterpret_cast<const ::t3c::protobuf::Engine&>(
      ::t3c::protobuf::_Engine_default_instance_);
}
inline const ::t3c::protobuf::Engine& t3c::eng() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.t3c.eng)
  return _internal_eng();
}
inline void t3c::unsafe_arena_set_allocated_eng(
    ::t3c::protobuf::Engine* eng) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.eng_);
  }
  _impl_.eng_ = eng;
  if (eng) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:t3c.protobuf.t3c.eng)
}
inline ::t3c::protobuf::Engine* t3c::release_eng() {
  
  ::t3c::protobuf::Engine* temp = _impl_.eng_;
  _impl_.eng_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::t3c::protobuf::Engine* t3c::unsafe_arena_release_eng() {
  // @@protoc_insertion_point(field_release:t3c.protobuf.t3c.eng)
  
  ::t3c::protobuf::Engine* temp = _impl_.eng_;
  _impl_.eng_ = nullptr;
  return temp;
}
inline ::t3c::protobuf::Engine* t3c::_internal_mutable_eng() {
  
  if (_impl_.eng_ == nullptr) {
    auto* p = CreateMaybeMessage<::t3c::protobuf::Engine>(GetArenaForAllocation());
    _impl_.eng_ = p;
  }
  return _impl_.eng_;
}
inline ::t3c::protobuf::Engine* t3c::mutable_eng() {
  ::t3c::protobuf::Engine* _msg = _internal_mutable_eng();
  // @@protoc_insertion_point(field_mutable:t3c.protobuf.t3c.eng)
  return _msg;
}
inline void t3c::set_allocated_eng(::t3c::protobuf::Engine* eng) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.eng_;
  }
  if (eng) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(eng);
    if (message_arena != submessage_arena) {
      eng = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, eng, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.eng_ = eng;
  // @@protoc_insertion_point(field_set_allocated:t3c.protobuf.t3c.eng)
}

// -------------------------------------------------------------------

// Phys_state

// float lat = 1;
inline void Phys_state::clear_lat() {
  _impl_.lat_ = 0;
}
inline float Phys_state::_internal_lat() const {
  return _impl_.lat_;
}
inline float Phys_state::lat() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.Phys_state.lat)
  return _internal_lat();
}
inline void Phys_state::_internal_set_lat(float value) {
  
  _impl_.lat_ = value;
}
inline void Phys_state::set_lat(float value) {
  _internal_set_lat(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.Phys_state.lat)
}

// float lon = 2;
inline void Phys_state::clear_lon() {
  _impl_.lon_ = 0;
}
inline float Phys_state::_internal_lon() const {
  return _impl_.lon_;
}
inline float Phys_state::lon() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.Phys_state.lon)
  return _internal_lon();
}
inline void Phys_state::_internal_set_lon(float value) {
  
  _impl_.lon_ = value;
}
inline void Phys_state::set_lon(float value) {
  _internal_set_lon(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.Phys_state.lon)
}

// float heading = 3;
inline void Phys_state::clear_heading() {
  _impl_.heading_ = 0;
}
inline float Phys_state::_internal_heading() const {
  return _impl_.heading_;
}
inline float Phys_state::heading() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.Phys_state.heading)
  return _internal_heading();
}
inline void Phys_state::_internal_set_heading(float value) {
  
  _impl_.heading_ = value;
}
inline void Phys_state::set_heading(float value) {
  _internal_set_heading(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.Phys_state.heading)
}

// float alt = 4;
inline void Phys_state::clear_alt() {
  _impl_.alt_ = 0;
}
inline float Phys_state::_internal_alt() const {
  return _impl_.alt_;
}
inline float Phys_state::alt() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.Phys_state.alt)
  return _internal_alt();
}
inline void Phys_state::_internal_set_alt(float value) {
  
  _impl_.alt_ = value;
}
inline void Phys_state::set_alt(float value) {
  _internal_set_alt(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.Phys_state.alt)
}

// float speed = 5;
inline void Phys_state::clear_speed() {
  _impl_.speed_ = 0;
}
inline float Phys_state::_internal_speed() const {
  return _impl_.speed_;
}
inline float Phys_state::speed() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.Phys_state.speed)
  return _internal_speed();
}
inline void Phys_state::_internal_set_speed(float value) {
  
  _impl_.speed_ = value;
}
inline void Phys_state::set_speed(float value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.Phys_state.speed)
}

// string mode = 6;
inline void Phys_state::clear_mode() {
  _impl_.mode_.ClearToEmpty();
}
inline const std::string& Phys_state::mode() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.Phys_state.mode)
  return _internal_mode();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Phys_state::set_mode(ArgT0&& arg0, ArgT... args) {
 
 _impl_.mode_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:t3c.protobuf.Phys_state.mode)
}
inline std::string* Phys_state::mutable_mode() {
  std::string* _s = _internal_mutable_mode();
  // @@protoc_insertion_point(field_mutable:t3c.protobuf.Phys_state.mode)
  return _s;
}
inline const std::string& Phys_state::_internal_mode() const {
  return _impl_.mode_.Get();
}
inline void Phys_state::_internal_set_mode(const std::string& value) {
  
  _impl_.mode_.Set(value, GetArenaForAllocation());
}
inline std::string* Phys_state::_internal_mutable_mode() {
  
  return _impl_.mode_.Mutable(GetArenaForAllocation());
}
inline std::string* Phys_state::release_mode() {
  // @@protoc_insertion_point(field_release:t3c.protobuf.Phys_state.mode)
  return _impl_.mode_.Release();
}
inline void Phys_state::set_allocated_mode(std::string* mode) {
  if (mode != nullptr) {
    
  } else {
    
  }
  _impl_.mode_.SetAllocated(mode, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.mode_.IsDefault()) {
    _impl_.mode_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:t3c.protobuf.Phys_state.mode)
}

// -------------------------------------------------------------------

// RC

// int32 throttle = 1;
inline void RC::clear_throttle() {
  _impl_.throttle_ = 0;
}
inline int32_t RC::_internal_throttle() const {
  return _impl_.throttle_;
}
inline int32_t RC::throttle() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.RC.throttle)
  return _internal_throttle();
}
inline void RC::_internal_set_throttle(int32_t value) {
  
  _impl_.throttle_ = value;
}
inline void RC::set_throttle(int32_t value) {
  _internal_set_throttle(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.RC.throttle)
}

// int32 rudder = 2;
inline void RC::clear_rudder() {
  _impl_.rudder_ = 0;
}
inline int32_t RC::_internal_rudder() const {
  return _impl_.rudder_;
}
inline int32_t RC::rudder() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.RC.rudder)
  return _internal_rudder();
}
inline void RC::_internal_set_rudder(int32_t value) {
  
  _impl_.rudder_ = value;
}
inline void RC::set_rudder(int32_t value) {
  _internal_set_rudder(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.RC.rudder)
}

// int32 roll = 3;
inline void RC::clear_roll() {
  _impl_.roll_ = 0;
}
inline int32_t RC::_internal_roll() const {
  return _impl_.roll_;
}
inline int32_t RC::roll() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.RC.roll)
  return _internal_roll();
}
inline void RC::_internal_set_roll(int32_t value) {
  
  _impl_.roll_ = value;
}
inline void RC::set_roll(int32_t value) {
  _internal_set_roll(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.RC.roll)
}

// int32 pitch = 4;
inline void RC::clear_pitch() {
  _impl_.pitch_ = 0;
}
inline int32_t RC::_internal_pitch() const {
  return _impl_.pitch_;
}
inline int32_t RC::pitch() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.RC.pitch)
  return _internal_pitch();
}
inline void RC::_internal_set_pitch(int32_t value) {
  
  _impl_.pitch_ = value;
}
inline void RC::set_pitch(int32_t value) {
  _internal_set_pitch(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.RC.pitch)
}

// -------------------------------------------------------------------

// Engine

// bool key = 1;
inline void Engine::clear_key() {
  _impl_.key_ = false;
}
inline bool Engine::_internal_key() const {
  return _impl_.key_;
}
inline bool Engine::key() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.Engine.key)
  return _internal_key();
}
inline void Engine::_internal_set_key(bool value) {
  
  _impl_.key_ = value;
}
inline void Engine::set_key(bool value) {
  _internal_set_key(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.Engine.key)
}

// int32 rpm = 2;
inline void Engine::clear_rpm() {
  _impl_.rpm_ = 0;
}
inline int32_t Engine::_internal_rpm() const {
  return _impl_.rpm_;
}
inline int32_t Engine::rpm() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.Engine.rpm)
  return _internal_rpm();
}
inline void Engine::_internal_set_rpm(int32_t value) {
  
  _impl_.rpm_ = value;
}
inline void Engine::set_rpm(int32_t value) {
  _internal_set_rpm(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.Engine.rpm)
}

// bool eng_state = 3;
inline void Engine::clear_eng_state() {
  _impl_.eng_state_ = false;
}
inline bool Engine::_internal_eng_state() const {
  return _impl_.eng_state_;
}
inline bool Engine::eng_state() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.Engine.eng_state)
  return _internal_eng_state();
}
inline void Engine::_internal_set_eng_state(bool value) {
  
  _impl_.eng_state_ = value;
}
inline void Engine::set_eng_state(bool value) {
  _internal_set_eng_state(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.Engine.eng_state)
}

// int32 fuel = 4;
inline void Engine::clear_fuel() {
  _impl_.fuel_ = 0;
}
inline int32_t Engine::_internal_fuel() const {
  return _impl_.fuel_;
}
inline int32_t Engine::fuel() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.Engine.fuel)
  return _internal_fuel();
}
inline void Engine::_internal_set_fuel(int32_t value) {
  
  _impl_.fuel_ = value;
}
inline void Engine::set_fuel(int32_t value) {
  _internal_set_fuel(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.Engine.fuel)
}

// int32 uptime = 5;
inline void Engine::clear_uptime() {
  _impl_.uptime_ = 0;
}
inline int32_t Engine::_internal_uptime() const {
  return _impl_.uptime_;
}
inline int32_t Engine::uptime() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.Engine.uptime)
  return _internal_uptime();
}
inline void Engine::_internal_set_uptime(int32_t value) {
  
  _impl_.uptime_ = value;
}
inline void Engine::set_uptime(int32_t value) {
  _internal_set_uptime(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.Engine.uptime)
}

// int32 mot_state = 6;
inline void Engine::clear_mot_state() {
  _impl_.mot_state_ = 0;
}
inline int32_t Engine::_internal_mot_state() const {
  return _impl_.mot_state_;
}
inline int32_t Engine::mot_state() const {
  // @@protoc_insertion_point(field_get:t3c.protobuf.Engine.mot_state)
  return _internal_mot_state();
}
inline void Engine::_internal_set_mot_state(int32_t value) {
  
  _impl_.mot_state_ = value;
}
inline void Engine::set_mot_state(int32_t value) {
  _internal_set_mot_state(value);
  // @@protoc_insertion_point(field_set:t3c.protobuf.Engine.mot_state)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace t3c

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::t3c::protobuf::Frame> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::t3c::protobuf::Frame>() {
  return ::t3c::protobuf::Frame_descriptor();
}
template <> struct is_proto_enum< ::t3c::protobuf::Mot> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::t3c::protobuf::Mot>() {
  return ::t3c::protobuf::Mot_descriptor();
}
template <> struct is_proto_enum< ::t3c::protobuf::Sys_mode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::t3c::protobuf::Sys_mode>() {
  return ::t3c::protobuf::Sys_mode_descriptor();
}
template <> struct is_proto_enum< ::t3c::protobuf::Effector> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::t3c::protobuf::Effector>() {
  return ::t3c::protobuf::Effector_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_T3C_2eproto
